default_velocity_scaling_factor: 0.40
default_acceleration_scaling_factor: 0.40
 
joint_limits:
  ur5e_shoulder_pan_joint:
    # acceleration limits are not publicly available
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 15.0
    has_deceleration_limits: true
    max_deceleration: -15.0
    has_jerk_limits: true
    max_jerk: 300.0
    has_effort_limits: true
    max_effort: 56.0
  ur5e_shoulder_lift_joint:
    # acceleration limits are not publicly available
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 15.0
    has_deceleration_limits: true
    max_deceleration: -15.0
    has_jerk_limits: true
    max_jerk: 300.0
    has_effort_limits: true
    max_effort: 56.0
  ur5e_elbow_joint:
    # acceleration limits are not publicly available
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 15.0
    has_deceleration_limits: true
    max_deceleration: -15.0
    has_jerk_limits: true
    max_jerk: 300.0
    has_effort_limits: true
    max_effort: 56.0
  ur5e_wrist_1_joint:
    # acceleration limits are not publicly available
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 15.0
    has_deceleration_limits: true
    max_deceleration: -15.0
    has_jerk_limits: true
    max_jerk: 300.0
    has_effort_limits: true
    max_effort: 56.0
  ur5e_wrist_2_joint:
    # acceleration limits are not publicly available
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 15.0
    has_deceleration_limits: true
    max_deceleration: -15.0
    has_jerk_limits: true
    max_jerk: 300.0
    has_effort_limits: true
    max_effort: 56.0
  ur5e_wrist_3_joint:
    # acceleration limits are not publicly available
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 15.0
    has_deceleration_limits: true
    max_deceleration: -15.0
    has_jerk_limits: true
    max_jerk: 300.0
    has_effort_limits: true
    max_effort: 56.0
  gripper1_joint:
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 15.0
    has_deceleration_limits: true
    max_deceleration: -15.0
    has_jerk_limits: true
    max_jerk: 300.0
    has_effort_limits: true
    max_effort: 56.0
  gripper2_joint:
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 15.0
    has_deceleration_limits: true
    max_deceleration: -15.0
    has_jerk_limits: true
    max_jerk: 300.0
    has_effort_limits: true
    max_effort: 56.0