trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01
  execution_duration_monitoring: true

# This file configures the controller management for MoveIt, specifying which controllers are available,
# the joints each controller handles, and the type of interface (e.g. FollowJointTrajectory).
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager  # Specifies the controller manager to use.
 
# Define the controllers configured using the ROS 2 Control framework.
moveit_simple_controller_manager:
  controller_names:
    - arm_controller   # Name of the controller for the robotic arm.
    - gripper1_action_controller # Name of the controller for the gripper
    - gripper2_action_controller # Name of the controller for the gripper
 
  # Configuration for the arm_controller.
  arm_controller:
    action_ns: follow_joint_trajectory   # ROS action namespace to which MoveIt sends trajectory commands.
    type: FollowJointTrajectory          # Type of the controller interface; follows a joint trajectory.
    default: true                        # This controller is the default for the joints listed below.
    joints:                              # List of joints that the arm_controller manages.
      - ur5e_shoulder_pan_joint
      - ur5e_shoulder_lift_joint
      - ur5e_elbow_joint
      - ur5e_wrist_1_joint
      - ur5e_wrist_2_joint
      - ur5e_wrist_3_joint
 
  # Configuration for the gripper_action_controller.
  gripper1_action_controller:
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    joints:
      - gripper1_joint

  # Configuration for the gripper_action_controller.
  gripper2_action_controller:
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    joints:
      - gripper2_joint